### PR TITLE
Support List Transfers

### PR DESCRIPTION
**Pull request by natercioluno**
This includes some documentation updates to better explain transfers.

### CODE REVIEW

**Review by edfiqri — APPROVED** [review]

**Review by edfiqri — APPROVED** [review]

**Review by edfiqri — APPROVED** [review]
great

**Review by edfiqri — APPROVED** [review]
great

**Review by edfiqri — APPROVED** [review]
great

**Review by edfiqri — APPROVED** [review]
great

**Comment by edfiqri** [comment]
good

**Comment by edfiqri** [comment]
good

**Review by edfiqri — APPROVED** [review]
good

**Comment by neilgarb** [comment]
I've updated the API in 0.0.26.

**Pull request closed without merging**
